<?xml version="1.0" ?>
<testsuite errors="0" failures="1" name="test.testcases.FailedTestCase" tests="1" time="0.000">
	<testcase classname="test.testcases.FailedTestCase" name="test_failure" time="0.000">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "{{PATH}}/test/testcases.py", line 21, in test_failure
    self.assertTrue(None)
AssertionError
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[another text
]]>	</system-err>
</testsuite>
